### PR TITLE
Text edits for next steps

### PR DESCRIPTION
**Pull request by GaryRidgway**
tracks https://github.com/uiowa/admissions-next-steps/issues/23

### CODE REVIEW

**Comment by bspeare** [comment]
I can test this.

**Comment by bspeare** [comment]
Looks good, I noticed this one:

Screen Shot 2022-01-28 at 3 58 37 PM

In his notes he said "remove the placement rates on hover" so I think we just remove them all?  Did you notice that comment?


Also unrelated, this padding at a lower breakpoint is a bit too much, maybe there's a breakpoint we can adjust for an easy fix?


Screen Shot 2022-01-28 at 4 01 03 PM

**Comment by GaryRidgway** [comment]
@bspeare would you take another look at this? i think i solved the problems you listed!

**Review by bspeare — APPROVED** [review]
Looks good, thanks @GaryRidgway!

**Pull request merged**
